services:
  inventory-postgres:
    container_name: inventory-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: password  # pragma: allowlist secret
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

volumes:
  inventory_postgres_data:
