ALTER TABLE inventories
    ADD COLUMN price       INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN description TEXT        NOT NULL DEFAULT '',
    ADD COLUMN image_key   TEXT        NULL,
    ADD COLUMN created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN updated_at  TIMESTAMPTZ NOT NULL DEFAULT now();

-- 既存の素の INTEGER PRIMARY KEY を IDENTITY 化する。DEFAULT なので
-- seed のような id 直指定の INSERT と共存できる。
ALTER TABLE inventories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('inventories', 'id'), COALESCE((SELECT MAX(id) FROM inventories), 0) + 1, false);

UPDATE inventories SET price = 2000, description = 'コットン100%の定番半袖Tシャツ。オールシーズン使える一枚。' WHERE id = 1;
UPDATE inventories SET price = 2000, description = '定番半袖Tシャツのゆったりサイズ。' WHERE id = 2;
UPDATE inventories SET price = 6800, description = '丈夫なデニム素材のストレートパンツ。' WHERE id = 3;
UPDATE inventories SET price = 8900, description = '長時間歩いても疲れにくい軽量スニーカー。' WHERE id = 4;
UPDATE inventories SET price = 1500, description = 'コーディネートのアクセントになるキャップ。' WHERE id = 5;
