CREATE TABLE IF NOT EXISTS media_assets (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key  TEXT NOT NULL UNIQUE,
    status       TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed')),
    product_id   INTEGER NULL REFERENCES products(id) ON DELETE SET NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_media_assets_pending_expires
    ON media_assets (expires_at)
    WHERE status = 'pending';
